import { useState } from "react";
import { Alert, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { formatMoney, useFinance } from "@/lib/finance-context";

export default function SettingsScreen() {
  const { openingCash, openingBank, setOpeningBalances, cashBalance, bankBalance } = useFinance();
  const [cash, setCash] = useState(String(openingCash));
  const [bank, setBank] = useState(String(openingBank));
  const save = () => { setOpeningBalances(Number(cash) || 0, Number(bank) || 0); Alert.alert("تم الحفظ", "تم تحديث الأرصدة الافتتاحية."); };
  return <ScreenContainer className="px-5 pt-5"><Text style={styles.eyebrow}>تحكم بسيط وواضح</Text><Text style={styles.title}>الإعدادات</Text><View style={styles.help}><Text style={styles.helpTitle}>كيف يعمل الدفتر؟</Text><Text style={styles.helpText}>المدين هو المبلغ الداخل إليك، والدائن هو المبلغ الخارج منك. التحويل للبنك ينقل المبلغ من النقد إلى البنك ولا يُحسب مصروفًا.</Text></View><Text style={styles.section}>الأرصدة الافتتاحية</Text><Text style={styles.caption}>اكتب ما لديك قبل بدء استخدام «مصروفي».</Text><View style={styles.card}><Text style={styles.label}>الرصيد النقدي عند البداية</Text><TextInput value={cash} onChangeText={setCash} keyboardType="decimal-pad" style={styles.input} /><Text style={styles.label}>الرصيد البنكي عند البداية</Text><TextInput value={bank} onChangeText={setBank} keyboardType="decimal-pad" style={styles.input} /><Pressable onPress={save} style={({ pressed }) => [styles.button, pressed && { opacity: 0.75 }]}><Text style={styles.buttonText}>حفظ الأرصدة</Text></Pressable></View><Text style={styles.section}>الوضع الحالي</Text><View style={styles.status}><View><Text style={styles.statusLabel}>نقدي</Text><Text style={styles.statusValue}>{formatMoney(cashBalance)}</Text></View><View><Text style={styles.statusLabel}>بنكي</Text><Text style={styles.statusValue}>{formatMoney(bankBalance)}</Text></View></View></ScreenContainer>;
}
const styles = StyleSheet.create({ eyebrow: { color: "#0F9B8E", fontSize: 14, fontWeight: "700", textAlign: "right" }, title: { color: "#17212B", fontSize: 30, fontWeight: "800", textAlign: "right", marginTop: 4, marginBottom: 17 }, help: { backgroundColor: "#E1F5F1", padding: 17, borderRadius: 18, alignItems: "flex-end" }, helpTitle: { color: "#0F6E66", fontSize: 15, fontWeight: "800" }, helpText: { color: "#347D76", textAlign: "right", fontSize: 12, lineHeight: 20, marginTop: 5 }, section: { color: "#17212B", fontSize: 18, fontWeight: "800", textAlign: "right", marginTop: 24 }, caption: { color: "#667085", textAlign: "right", fontSize: 12, marginTop: 5, marginBottom: 10 }, card: { backgroundColor: "#FFFFFF", borderRadius: 18, padding: 17 }, label: { color: "#667085", textAlign: "right", fontSize: 12, fontWeight: "700", marginBottom: 6, marginTop: 4 }, input: { backgroundColor: "#F6F8FB", borderWidth: 1, borderColor: "#E1E7EF", borderRadius: 11, padding: 12, color: "#17212B", textAlign: "right", fontSize: 16, marginBottom: 11 }, button: { backgroundColor: "#17365D", borderRadius: 12, padding: 13, alignItems: "center", marginTop: 3 }, buttonText: { color: "#FFFFFF", fontWeight: "800" }, status: { backgroundColor: "#FFFFFF", borderRadius: 18, padding: 18, flexDirection: "row-reverse", justifyContent: "space-between" }, statusLabel: { color: "#667085", fontSize: 12, textAlign: "right" }, statusValue: { color: "#17365D", fontWeight: "800", fontSize: 16, marginTop: 6, textAlign: "right" } });
