import { useState } from "react";
import { Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { formatMoney, useFinance } from "@/lib/finance-context";

export default function SettingsScreen() {
  const { accounts, bankAccounts, accountBalances, openingCash, openingBank, setOpeningBalances, addBankAccount, cashBalance, bankBalance } = useFinance();
  const [cash, setCash] = useState(String(openingCash));
  const [bank, setBank] = useState(String(openingBank));
  const [bankName, setBankName] = useState("");
  const [bankOpening, setBankOpening] = useState("");
  const save = () => { setOpeningBalances(Number(cash) || 0, Number(bank) || 0); Alert.alert("تم الحفظ", "تم تحديث أرصدة النقد والبنك الأساسي."); };
  const addBank = () => { const amount = Number(bankOpening.replace(",", ".")) || 0; if (!bankName.trim()) return Alert.alert("اكتب اسم البنك", "أدخل اسمًا واضحًا للحساب البنكي."); addBankAccount(bankName, amount); setBankName(""); setBankOpening(""); Alert.alert("تمت الإضافة", `تمت إضافة حساب ${bankName.trim()}.`); };
  return <ScreenContainer className="px-5 pt-5"><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={{ paddingBottom: 35 }}><Text style={styles.eyebrow}>تحكم بسيط وواضح</Text><Text style={styles.title}>الإعدادات</Text><View style={styles.help}><Text style={styles.helpTitle}>حساباتك المالية</Text><Text style={styles.helpText}>يمكنك الاحتفاظ بالنقد وعدة بنوك. التحويلات تعمل في الاتجاهين وبين أي حسابين، ولا تُحسب كمصروف.</Text></View><Text style={styles.section}>الأرصدة الافتتاحية</Text><Text style={styles.caption}>اكتب ما لديك قبل بدء استخدام «مصروفي».</Text><View style={styles.card}><Text style={styles.label}>الرصيد النقدي عند البداية</Text><TextInput value={cash} onChangeText={setCash} keyboardType="decimal-pad" style={styles.input} /><Text style={styles.label}>الرصيد البنكي الأساسي عند البداية</Text><TextInput value={bank} onChangeText={setBank} keyboardType="decimal-pad" style={styles.input} /><Pressable onPress={save} style={({ pressed }) => [styles.button, pressed && { opacity: 0.75 }]}><Text style={styles.buttonText}>حفظ الأرصدة</Text></Pressable></View><Text style={styles.section}>إضافة بنك جديد</Text><Text style={styles.caption}>اكتب اسم البنك ورصيده الافتتاحي، ثم سيظهر كحساب مستقل في التحويلات.</Text><View style={styles.card}><Text style={styles.label}>اسم البنك</Text><TextInput value={bankName} onChangeText={setBankName} placeholder="مثال: البنك العربي" placeholderTextColor="#98A2B3" style={styles.input} /><Text style={styles.label}>الرصيد الافتتاحي</Text><TextInput value={bankOpening} onChangeText={setBankOpening} keyboardType="decimal-pad" placeholder="0.00" placeholderTextColor="#98A2B3" style={styles.input} /><Pressable onPress={addBank} style={({ pressed }) => [styles.button, pressed && { opacity: 0.75 }]}><Text style={styles.buttonText}>إضافة الحساب البنكي</Text></Pressable></View><Text style={styles.section}>أرصدة الحسابات</Text><View style={styles.status}>{accounts.map((account) => <View key={account.id} style={styles.accountLine}><Text style={styles.statusValue}>{formatMoney(accountBalances[account.id] ?? 0)}</Text><Text style={styles.statusLabel}>{account.name}</Text></View>)}</View><Text style={styles.totals}>النقد: {formatMoney(cashBalance)} · مجموع البنوك: {formatMoney(bankBalance)}</Text></ScrollView></ScreenContainer>;
}
const styles = StyleSheet.create({ eyebrow: { color: "#0F9B8E", fontSize: 14, fontWeight: "700", textAlign: "right" }, title: { color: "#17212B", fontSize: 30, fontWeight: "800", textAlign: "right", marginTop: 4, marginBottom: 17 }, help: { backgroundColor: "#E1F5F1", padding: 17, borderRadius: 18, alignItems: "flex-end" }, helpTitle: { color: "#0F6E66", fontSize: 15, fontWeight: "800" }, helpText: { color: "#347D76", textAlign: "right", fontSize: 12, lineHeight: 20, marginTop: 5 }, section: { color: "#17212B", fontSize: 18, fontWeight: "800", textAlign: "right", marginTop: 24 }, caption: { color: "#667085", textAlign: "right", fontSize: 12, lineHeight: 18, marginTop: 5, marginBottom: 10 }, card: { backgroundColor: "#FFFFFF", borderRadius: 18, padding: 17 }, label: { color: "#667085", textAlign: "right", fontSize: 12, fontWeight: "700", marginBottom: 6, marginTop: 4 }, input: { backgroundColor: "#F6F8FB", borderWidth: 1, borderColor: "#E1E7EF", borderRadius: 11, padding: 12, color: "#17212B", textAlign: "right", fontSize: 16, marginBottom: 11 }, button: { backgroundColor: "#17365D", borderRadius: 12, padding: 13, alignItems: "center", marginTop: 3 }, buttonText: { color: "#FFFFFF", fontWeight: "800" }, status: { backgroundColor: "#FFFFFF", borderRadius: 18, padding: 18, gap: 12 }, accountLine: { flexDirection: "row-reverse", justifyContent: "space-between", borderBottomWidth: 1, borderBottomColor: "#EDF1F5", paddingBottom: 9 }, statusLabel: { color: "#667085", fontSize: 12, textAlign: "right" }, statusValue: { color: "#17365D", fontWeight: "800", fontSize: 16, textAlign: "right" }, totals: { color: "#667085", textAlign: "right", fontSize: 12, marginTop: 10 } });
