export type Currency = { code: string; name: string; symbol: string };

export const CURRENCIES: Currency[] = [
  { code: "JOD", name: "الدينار الأردني", symbol: "د.أ" },
  { code: "AED", name: "الدرهم الإماراتي", symbol: "د.إ" },
  { code: "SAR", name: "الريال السعودي", symbol: "ر.س" },
  { code: "QAR", name: "الريال القطري", symbol: "ر.ق" },
  { code: "KWD", name: "الدينار الكويتي", symbol: "د.ك" },
  { code: "BHD", name: "الدينار البحريني", symbol: "د.ب" },
  { code: "OMR", name: "الريال العماني", symbol: "ر.ع" },
  { code: "IQD", name: "الدينار العراقي", symbol: "ع.ع" },
  { code: "EGP", name: "الجنيه المصري", symbol: "ج.م" },
  { code: "LBP", name: "الليرة اللبنانية", symbol: "ل.ل" },
  { code: "SYP", name: "الليرة السورية", symbol: "ل.س" },
  { code: "MAD", name: "الدرهم المغربي", symbol: "د.م" },
  { code: "TND", name: "الدينار التونسي", symbol: "د.ت" },
  { code: "DZD", name: "الدينار الجزائري", symbol: "دج" },
  { code: "LYD", name: "الدينار الليبي", symbol: "ل.د" },
  { code: "SDG", name: "الجنيه السوداني", symbol: "ج.س" },
  { code: "TRY", name: "الليرة التركية", symbol: "₺" },
  { code: "USD", name: "الدولار الأمريكي", symbol: "$" },
  { code: "CAD", name: "الدولار الكندي", symbol: "C$" },
  { code: "AUD", name: "الدولار الأسترالي", symbol: "A$" },
  { code: "NZD", name: "الدولار النيوزيلندي", symbol: "NZ$" },
  { code: "EUR", name: "اليورو", symbol: "€" },
  { code: "GBP", name: "الجنيه الإسترليني", symbol: "£" },
  { code: "CHF", name: "الفرنك السويسري", symbol: "CHF" },
  { code: "SEK", name: "الكرونة السويدية", symbol: "kr" },
  { code: "NOK", name: "الكرونة النرويجية", symbol: "kr" },
  { code: "DKK", name: "الكرونة الدنماركية", symbol: "kr" },
  { code: "PLN", name: "الزلوتي البولندي", symbol: "zł" },
  { code: "CZK", name: "الكورونا التشيكية", symbol: "Kč" },
  { code: "HUF", name: "الفورنت المجري", symbol: "Ft" },
  { code: "RON", name: "الليو الروماني", symbol: "lei" },
  { code: "RUB", name: "الروبل الروسي", symbol: "₽" },
  { code: "UAH", name: "الهريفنيا الأوكرانية", symbol: "₴" },
  { code: "INR", name: "الروبية الهندية", symbol: "₹" },
  { code: "PKR", name: "الروبية الباكستانية", symbol: "₨" },
  { code: "BDT", name: "التاكا البنغلاديشي", symbol: "৳" },
  { code: "LKR", name: "الروبية السريلانكية", symbol: "Rs" },
  { code: "NPR", name: "الروبية النيبالية", symbol: "रू" },
  { code: "CNY", name: "اليوان الصيني", symbol: "¥" },
  { code: "JPY", name: "الين الياباني", symbol: "¥" },
  { code: "KRW", name: "الوون الكوري", symbol: "₩" },
  { code: "THB", name: "البات التايلندي", symbol: "฿" },
  { code: "MYR", name: "الرينغيت الماليزي", symbol: "RM" },
  { code: "IDR", name: "الروبية الإندونيسية", symbol: "Rp" },
  { code: "PHP", name: "البيزو الفلبيني", symbol: "₱" },
  { code: "VND", name: "الدونغ الفيتنامي", symbol: "₫" },
  { code: "SGD", name: "الدولار السنغافوري", symbol: "S$" },
  { code: "HKD", name: "دولار هونغ كونغ", symbol: "HK$" },
  { code: "TWD", name: "الدولار التايواني", symbol: "NT$" },
  { code: "ZAR", name: "الراند الجنوب أفريقي", symbol: "R" },
  { code: "NGN", name: "النيرة النيجيرية", symbol: "₦" },
  { code: "KES", name: "الشلن الكيني", symbol: "KSh" },
  { code: "GHS", name: "السيدي الغاني", symbol: "₵" },
  { code: "BRL", name: "الريال البرازيلي", symbol: "R$" },
  { code: "MXN", name: "البيزو المكسيكي", symbol: "Mex$" },
  { code: "ARS", name: "البيزو الأرجنتيني", symbol: "AR$" },
  { code: "CLP", name: "البيزو التشيلي", symbol: "CLP$" },
  { code: "COP", name: "البيزو الكولومبي", symbol: "COL$" },
  { code: "PEN", name: "السول البيروفي", symbol: "S/" },
  { code: "UYU", name: "البيزو الأوروغوياني", symbol: "$U" },
  { code: "ISK", name: "الكرونا الأيسلندية", symbol: "kr" },
  { code: "BGN", name: "الليف البلغاري", symbol: "лв" },
  { code: "RSD", name: "الدينار الصربي", symbol: "дин" },
  { code: "HRK", name: "الكونا الكرواتية", symbol: "kn" },
  { code: "GEL", name: "اللاري الجورجي", symbol: "₾" },
  { code: "AZN", name: "المانات الأذربيجاني", symbol: "₼" },
  { code: "KZT", name: "التنغي الكازاخستاني", symbol: "₸" },
  { code: "IRR", name: "الريال الإيراني", symbol: "﷼" },
  { code: "AFN", name: "الأفغاني", symbol: "؋" },
  { code: "ETB", name: "البِر الإثيوبي", symbol: "Br" },
  { code: "TZS", name: "الشلن التنزاني", symbol: "TSh" },
  { code: "UGX", name: "الشلن الأوغندي", symbol: "USh" },
  { code: "MUR", name: "الروبية الموريشيوسية", symbol: "₨" },
  { code: "JMD", name: "الدولار الجامايكي", symbol: "J$" },
  { code: "TTD", name: "دولار ترينيداد وتوباغو", symbol: "TT$" },
  { code: "BBD", name: "الدولار البربادوسي", symbol: "Bds$" },
  { code: "FJD", name: "الدولار الفيجي", symbol: "FJ$" },
  { code: "XOF", name: "فرنك غرب أفريقيا", symbol: "CFA" },
  { code: "XAF", name: "فرنك وسط أفريقيا", symbol: "FCFA" },
];

export const DEFAULT_CURRENCY = CURRENCIES[0];
export function findCurrency(code: string) { return CURRENCIES.find((item) => item.code === code) ?? DEFAULT_CURRENCY; }
