import { useMemo, useState } from "react";
import { Alert, FlatList, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { useFinance, formatMoney, type EntryType } from "@/lib/finance-context";
import { generateAndSharePdf } from "@/lib/pdf-reports";

export default function EntriesScreen() {
  const { entries, deleteEntry, exportEntries, accounts, currency } = useFinance();
  const money = (value: number): string => formatMoney(value, currency.symbol);
  const [query, setQuery] = useState("");
  const [filter, setFilter] = useState<"all" | EntryType>("all");
  const [selectedIds, setSelectedIds] = useState<string[]>([]);
  const filtered = useMemo(() => entries.filter((entry) => (filter === "all" || entry.type === filter) && `${entry.note} ${entry.date}`.toLocaleLowerCase().includes(query.toLocaleLowerCase())), [entries, filter, query]);
  const remove = (id: string) => Alert.alert("حذف العملية؟", "لن يمكن التراجع عن هذا الإجراء.", [{ text: "إلغاء", style: "cancel" }, { text: "حذف", style: "destructive", onPress: () => deleteEntry(id) }]);
  const toggleSelected = (id: string) => setSelectedIds((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id]);
  const exportSelected = () => generateAndSharePdf("تقرير العمليات المحددة", `عدد العمليات: ${selectedIds.length}`, entries.filter((entry) => selectedIds.includes(entry.id)), currency.symbol);
  return <ScreenContainer className="px-5 pt-5"><View style={styles.header}><Text style={styles.eyebrow}>السجل المالي</Text><Text style={styles.title}>الدفتر</Text></View>
    <View style={styles.searchWrap}><TextInput value={query} onChangeText={setQuery} placeholder="ابحث عن البيان أو التاريخ" placeholderTextColor="#98A2B3" style={styles.search} accessibilityLabel="البحث عن البيان" /><Pressable onPress={() => setQuery("")} style={styles.clear}><Text style={styles.clearText}>مسح</Text></Pressable></View>
    <View style={styles.filters}>{([['all', 'الكل'], ['debit', 'مدين'], ['credit', 'دائن'], ['transfer', 'تحويل']] as const).map(([value, label]) => <Pressable key={value} onPress={() => setFilter(value)} style={[styles.filter, filter === value && styles.filterActive]}><Text style={[styles.filterText, filter === value && styles.filterTextActive]}>{label}</Text></Pressable>)}</View>
    <View style={styles.actionsRow}><Pressable onPress={exportEntries} style={styles.action}><Text style={styles.actionText}>استخراج السجل</Text></Pressable><Pressable onPress={exportSelected} disabled={!selectedIds.length} style={[styles.action, !selectedIds.length && styles.actionDisabled]}><Text style={[styles.actionText, !selectedIds.length && styles.actionDisabledText]}>PDF المحدد ({selectedIds.length})</Text></Pressable></View>
    <FlatList data={filtered} keyExtractor={(item) => item.id} contentContainerStyle={{ paddingTop: 14, paddingBottom: 35 }} ListEmptyComponent={<View style={styles.empty}><Text style={styles.emptyTitle}>لا توجد نتائج</Text><Text style={styles.emptyText}>اكتب جزءًا من البيان للبحث داخل السجل.</Text></View>} renderItem={({ item }) => { const selected = selectedIds.includes(item.id); return <View style={[styles.row, selected && styles.rowSelected]}><Pressable onPress={() => toggleSelected(item.id)} style={[styles.checkbox, selected && styles.checkboxSelected]}><Text style={styles.checkmark}>{selected ? "✓" : ""}</Text></Pressable><View style={[styles.badge, { backgroundColor: item.type === "debit" ? "#E1F5F1" : item.type === "credit" ? "#FCE8E6" : "#E8EDF3" }]}><Text style={[styles.badgeText, { color: item.type === "debit" ? "#0F9B8E" : item.type === "credit" ? "#D95D55" : "#17365D" }]}>{item.type === "debit" ? "مدين" : item.type === "credit" ? "دائن" : "تحويل"}</Text></View><View style={styles.info}><Text style={styles.note}>{item.note}</Text><Text style={styles.meta}>{item.date} · {accounts.find((account) => account.id === (item.accountId ?? item.account))?.name ?? (item.account === "cash" ? "نقدي" : "بنكي")}</Text></View><View style={styles.actions}><Text style={[styles.amount, { color: item.type === "debit" ? "#0F9B8E" : "#D95D55" }]}>{item.type === "debit" ? "+" : "-"}{money(item.amount)}</Text><Pressable onPress={() => remove(item.id)}><Text style={styles.delete}>حذف</Text></Pressable></View></View>; }} />
  </ScreenContainer>;
}
const styles = StyleSheet.create({ header: { marginBottom: 14 }, eyebrow: { color: "#0F9B8E", fontSize: 14, fontWeight: "700", textAlign: "right" }, title: { color: "#17212B", fontSize: 30, fontWeight: "800", textAlign: "right", marginTop: 4 }, searchWrap: { flexDirection: "row-reverse", alignItems: "center", backgroundColor: "#FFFFFF", borderRadius: 14, borderWidth: 1, borderColor: "#E1E7EF" }, search: { flex: 1, padding: 13, textAlign: "right", color: "#17212B" }, clear: { paddingHorizontal: 12 }, clearText: { color: "#0F9B8E", fontWeight: "800", fontSize: 12 }, filters: { flexDirection: "row-reverse", gap: 7, marginVertical: 12 }, filter: { flex: 1, backgroundColor: "#E8EDF3", borderRadius: 10, paddingVertical: 9, alignItems: "center" }, filterActive: { backgroundColor: "#17365D" }, filterText: { color: "#667085", fontSize: 12, fontWeight: "700" }, filterTextActive: { color: "#FFFFFF" }, actionsRow: { flexDirection: "row-reverse", gap: 8 }, action: { flex: 1, borderWidth: 1, borderColor: "#0F9B8E", borderRadius: 12, padding: 11, alignItems: "center" }, actionText: { color: "#0F9B8E", fontWeight: "800", fontSize: 12 }, actionDisabled: { borderColor: "#D8E2EC" }, actionDisabledText: { color: "#98A2B3" }, row: { backgroundColor: "#FFFFFF", borderRadius: 15, padding: 11, marginBottom: 8, flexDirection: "row-reverse", alignItems: "center", gap: 8 }, rowSelected: { borderWidth: 1, borderColor: "#0F9B8E" }, checkbox: { width: 23, height: 23, borderRadius: 7, borderWidth: 1.5, borderColor: "#C5D0DC", alignItems: "center", justifyContent: "center" }, checkboxSelected: { backgroundColor: "#0F9B8E", borderColor: "#0F9B8E" }, checkmark: { color: "#FFFFFF", fontWeight: "900" }, badge: { borderRadius: 9, paddingHorizontal: 7, paddingVertical: 6 }, badgeText: { fontSize: 10, fontWeight: "800" }, info: { flex: 1 }, note: { color: "#17212B", textAlign: "right", fontSize: 13, fontWeight: "700" }, meta: { color: "#667085", textAlign: "right", fontSize: 11, marginTop: 4 }, actions: { alignItems: "flex-end" }, amount: { fontSize: 11, fontWeight: "800" }, delete: { color: "#98A2B3", fontSize: 11, marginTop: 5 }, empty: { backgroundColor: "#FFFFFF", borderRadius: 18, padding: 28, alignItems: "center", marginTop: 25 }, emptyTitle: { color: "#17212B", fontWeight: "800", fontSize: 16 }, emptyText: { color: "#667085", marginTop: 6 } });
