import { useMemo, useState } from "react";
import { Alert, FlatList, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { useFinance, formatMoney, type EntryType } from "@/lib/finance-context";

export default function EntriesScreen() {
  const { entries, deleteEntry, exportEntries } = useFinance();
  const [query, setQuery] = useState("");
  const [filter, setFilter] = useState<"all" | EntryType>("all");
  const filtered = useMemo(() => entries.filter((entry) => (filter === "all" || entry.type === filter) && `${entry.note} ${entry.date}`.includes(query)), [entries, filter, query]);
  const remove = (id: string) => Alert.alert("حذف العملية؟", "لن يمكن التراجع عن هذا الإجراء.", [{ text: "إلغاء", style: "cancel" }, { text: "حذف", style: "destructive", onPress: () => deleteEntry(id) }]);
  return <ScreenContainer className="px-5 pt-5"><View style={styles.header}><Text style={styles.eyebrow}>السجل المالي</Text><Text style={styles.title}>الدفتر</Text></View>
    <TextInput value={query} onChangeText={setQuery} placeholder="ابحث في البيان أو التاريخ" placeholderTextColor="#98A2B3" style={styles.search} />
    <View style={styles.filters}>{([["all", "الكل"], ["debit", "مدين"], ["credit", "دائن"], ["transfer", "تحويل"]] as const).map(([value, label]) => <Pressable key={value} onPress={() => setFilter(value)} style={[styles.filter, filter === value && styles.filterActive]}><Text style={[styles.filterText, filter === value && styles.filterTextActive]}>{label}</Text></Pressable>)}</View>
    <Pressable onPress={exportEntries} style={({ pressed }) => [styles.export, pressed && { opacity: 0.7 }]}><Text style={styles.exportText}>استخراج ومشاركة السجل</Text></Pressable>
    <FlatList data={filtered} keyExtractor={(item) => item.id} contentContainerStyle={{ paddingTop: 14, paddingBottom: 35 }} ListEmptyComponent={<View style={styles.empty}><Text style={styles.emptyTitle}>لا توجد نتائج</Text><Text style={styles.emptyText}>ستظهر العمليات هنا بعد تسجيلها.</Text></View>} renderItem={({ item }) => <View style={styles.row}><View style={[styles.badge, { backgroundColor: item.type === "debit" ? "#E1F5F1" : item.type === "credit" ? "#FCE8E6" : "#E8EDF3" }]}><Text style={[styles.badgeText, { color: item.type === "debit" ? "#0F9B8E" : item.type === "credit" ? "#D95D55" : "#17365D" }]}>{item.type === "debit" ? "مدين" : item.type === "credit" ? "دائن" : "تحويل"}</Text></View><View style={styles.info}><Text style={styles.note}>{item.note}</Text><Text style={styles.meta}>{item.date} · {item.account === "cash" ? "نقدي" : "بنكي"}</Text></View><View style={styles.actions}><Text style={[styles.amount, { color: item.type === "debit" ? "#0F9B8E" : "#D95D55" }]}>{item.type === "debit" ? "+" : "-"}{formatMoney(item.amount)}</Text><Pressable onPress={() => remove(item.id)}><Text style={styles.delete}>حذف</Text></Pressable></View></View>} />
  </ScreenContainer>;
}
const styles = StyleSheet.create({ header: { marginBottom: 14 }, eyebrow: { color: "#0F9B8E", fontSize: 14, fontWeight: "700", textAlign: "right" }, title: { color: "#17212B", fontSize: 30, fontWeight: "800", textAlign: "right", marginTop: 4 }, search: { backgroundColor: "#FFFFFF", borderRadius: 14, padding: 13, textAlign: "right", color: "#17212B", borderWidth: 1, borderColor: "#E1E7EF" }, filters: { flexDirection: "row-reverse", gap: 7, marginVertical: 12 }, filter: { flex: 1, backgroundColor: "#E8EDF3", borderRadius: 10, paddingVertical: 9, alignItems: "center" }, filterActive: { backgroundColor: "#17365D" }, filterText: { color: "#667085", fontSize: 12, fontWeight: "700" }, filterTextActive: { color: "#FFFFFF" }, export: { borderWidth: 1, borderColor: "#0F9B8E", borderRadius: 12, padding: 11, alignItems: "center" }, exportText: { color: "#0F9B8E", fontWeight: "800", fontSize: 13 }, row: { backgroundColor: "#FFFFFF", borderRadius: 15, padding: 13, marginBottom: 8, flexDirection: "row-reverse", alignItems: "center", gap: 9 }, badge: { borderRadius: 9, paddingHorizontal: 8, paddingVertical: 6 }, badgeText: { fontSize: 11, fontWeight: "800" }, info: { flex: 1 }, note: { color: "#17212B", textAlign: "right", fontSize: 14, fontWeight: "700" }, meta: { color: "#667085", textAlign: "right", fontSize: 11, marginTop: 4 }, actions: { alignItems: "flex-end" }, amount: { fontSize: 12, fontWeight: "800" }, delete: { color: "#98A2B3", fontSize: 11, marginTop: 6 }, empty: { backgroundColor: "#FFFFFF", borderRadius: 18, padding: 28, alignItems: "center", marginTop: 25 }, emptyTitle: { color: "#17212B", fontWeight: "800", fontSize: 16 }, emptyText: { color: "#667085", marginTop: 6 } });
